run:
  timeout: 5m
  go: "1.21"

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - gosimple
    - staticcheck
    - unused
    - ineffassign
  disable:
    - typecheck
    - gocyclo
    - dupl
    - gocognit

linters-settings:
  govet:
    check-shadowing: true
  errcheck:
    check-type-assertions: true
    check-blank: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - unused
        - errcheck
  max-issues-per-linter: 0
  max-same-issues: 0
